import { atlasWorldDestinationImages } from './atlasWorldAssets';
import { publicAsset } from './publicAsset';

export type AtlasPointStatus = 'visited' | 'locked';
export type AtlasRegion = 'china' | 'world';

export interface AtlasPoint {
  id: string;
  title: string;
  country?: string;
  routeId?: string;
  routeName?: string;
  status: AtlasPointStatus;
  image: string;
  x: number;
  y: number;
  rotation?: number;
  distance?: string;
  date?: string;
  moodQuote?: string;
  unlockHint?: string;
  routeType?: string;
  focusX?: number;
  focusY?: number;
  region?: AtlasRegion;
  regionGroup?: 'china';
  visibleInWorld?: boolean;
  visibleInRegion?: boolean;
  xWorld?: number;
  yWorld?: number;
  xRegion?: number;
  yRegion?: number;
}

export const atlasBackground = publicAsset('atlas/world-map-pacific.png');
export const atlasBarcode = publicAsset('atlas/barcode.png');

export const visitedAtlasSeeds: AtlasPoint[] = [
  {
    id: 'pingjiang-heritage-memory',
    title: 'Pingjiang',
    country: 'China',
    routeId: 'h1',
    routeName: 'Pingjiang Heritage Trail',
    status: 'locked',
    image: publicAsset('gudailuxian1.jpg'),
    x: 23,
    y: 24,
    xWorld: 23,
    yWorld: 24,
    xRegion: 17,
    yRegion: 29,
    rotation: -5,
    distance: '3.02 km',
    date: 'Visited',
    moodQuote: "Today's route felt like a page from a travel diary.",
    routeType: 'Historical',
    focusX: 23,
    focusY: 24,
    region: 'china',
    regionGroup: 'china',
    visibleInWorld: true,
    visibleInRegion: true,
  },
  {
    id: 'shantang-garden-memory',
    title: 'Shantang',
    country: 'China',
    routeId: 'h2',
    routeName: 'Shantang Garden Heritage Trail',
    status: 'locked',
    image: publicAsset('gudailuxian2.jpg'),
    x: 26,
    y: 44,
    xWorld: 26,
    yWorld: 44,
    xRegion: 25,
    yRegion: 35,
    rotation: 6,
    distance: '4.01 km',
    date: 'Visited',
    moodQuote: 'A canal-side memory, folded into a postcard.',
    routeType: 'Historical',
    focusX: 26,
    focusY: 44,
    region: 'china',
    regionGroup: 'china',
    visibleInWorld: false,
    visibleInRegion: true,
  },
  {
    id: 'bailuyuan-moonbay-memory',
    title: 'Moon Bay',
    country: 'China',
    routeId: 'm1',
    routeName: 'Bailuyuan Moon Bay Loop',
    status: 'locked',
    image: publicAsset('xiandailuxian1.jpg'),
    x: 23,
    y: 46,
    xWorld: 23,
    yWorld: 46,
    xRegion: 15,
    yRegion: 42,
    rotation: 4,
    distance: '6.01 km',
    date: 'Visited',
    moodQuote: 'A quiet run, a clearer mind.',
    routeType: 'Modern',
    focusX: 23,
    focusY: 46,
    region: 'china',
    regionGroup: 'china',
    visibleInWorld: false,
    visibleInRegion: true,
  },
  {
    id: 'yinshan-lake-memory',
    title: 'Yinshan',
    country: 'China',
    routeId: 'm2',
    routeName: 'Yinshan Lake Modern Loop',
    status: 'locked',
    image: publicAsset('xiandailuxian2.jpg'),
    x: 25,
    y: 47,
    xWorld: 25,
    yWorld: 47,
    xRegion: 30,
    yRegion: 46,
    rotation: -7,
    distance: '5.58 km',
    date: 'Visited',
    moodQuote: 'Small steps made the lake feel wider.',
    routeType: 'Modern',
    focusX: 25,
    focusY: 47,
    region: 'china',
    regionGroup: 'china',
    visibleInWorld: false,
    visibleInRegion: true,
  },
  {
    id: 'xjtlu-campus-memory',
    title: 'XJTLU',
    country: 'China',
    routeId: 'xjtlu-test',
    routeName: 'XJTLU Campus Test Route',
    status: 'locked',
    image: publicAsset('1.jpg'),
    x: 31,
    y: 33,
    xWorld: 31,
    yWorld: 33,
    xRegion: 21,
    yRegion: 44,
    rotation: -2,
    distance: '3.44 km',
    date: '04 May 2026',
    moodQuote: 'A small route became a lasting memory.',
    routeType: 'Historical Test',
    focusX: 31,
    focusY: 33,
    region: 'china',
    regionGroup: 'china',
    visibleInWorld: true,
    visibleInRegion: true,
  },
];

export const lockedAtlasPoints: AtlasPoint[] = [
  {
    id: 'future-america-new-york',
    title: 'New York Skyline Route',
    country: 'America',
    status: 'locked',
    image: atlasWorldDestinationImages.americaNewYork,
    x: 74,
    y: 38,
    rotation: -5,
    distance: '180 km',
    date: '--/--/----',
    unlockHint: 'Future destination in North America.',
    routeType: 'Future',
    focusX: 74,
    focusY: 38,
    region: 'world',
    visibleInWorld: true,
  },
  {
    id: 'future-america-river',
    title: 'Brooklyn River Route',
    country: 'America',
    status: 'locked',
    image: atlasWorldDestinationImages.americaRiver,
    x: 80,
    y: 44,
    rotation: 6,
    distance: '190 km',
    date: '--/--/----',
    unlockHint: 'Future destination in North America.',
    routeType: 'Future',
    focusX: 80,
    focusY: 44,
    region: 'world',
    visibleInWorld: true,
  },
  {
    id: 'future-south-america-rio',
    title: 'Rio Heights Route',
    country: 'South America',
    status: 'locked',
    image: atlasWorldDestinationImages.southAmericaRio,
    x: 86,
    y: 67,
    rotation: -7,
    distance: '210 km',
    date: '--/--/----',
    unlockHint: 'Future destination in South America.',
    routeType: 'Future',
    focusX: 86,
    focusY: 67,
    region: 'world',
    visibleInWorld: true,
  },
  {
    id: 'future-africa-kilimanjaro',
    title: 'Kilimanjaro Memory',
    country: 'Africa',
    status: 'locked',
    image: atlasWorldDestinationImages.africaKilimanjaro,
    x: 5,
    y: 57,
    rotation: 5,
    distance: '240 km',
    date: '--/--/----',
    unlockHint: 'Future destination in Africa.',
    routeType: 'Future',
    focusX: 5,
    focusY: 57,
    region: 'world',
    visibleInWorld: true,
  },
  {
    id: 'future-africa-savanna',
    title: 'Savanna Sky Route',
    country: 'Africa',
    status: 'locked',
    image: atlasWorldDestinationImages.africaSavanna,
    x: 10,
    y: 64,
    rotation: -4,
    distance: '260 km',
    date: '--/--/----',
    unlockHint: 'Future destination in Africa.',
    routeType: 'Future',
    focusX: 10,
    focusY: 64,
    region: 'world',
    visibleInWorld: true,
  },
  {
    id: 'future-europe-river',
    title: 'European River Route',
    country: 'Europe',
    status: 'locked',
    image: atlasWorldDestinationImages.europeRiver,
    x: 5,
    y: 31,
    rotation: -3,
    distance: '160 km',
    date: '--/--/----',
    unlockHint: 'Future destination in Europe.',
    routeType: 'Future',
    focusX: 5,
    focusY: 31,
    region: 'world',
    visibleInWorld: true,
  },
  {
    id: 'future-europe-paris',
    title: 'Eiffel Memory Route',
    country: 'Europe',
    status: 'locked',
    image: atlasWorldDestinationImages.europeParis,
    x: 11,
    y: 35,
    rotation: 6,
    distance: '170 km',
    date: '--/--/----',
    unlockHint: 'Future destination in Europe.',
    routeType: 'Future',
    focusX: 11,
    focusY: 35,
    region: 'world',
    visibleInWorld: true,
  },
];
